### ISSUE TITLE
Leaving for a month

### ISSUE THREAD

**Issue by nibsbin** [SnpM/Lockstep-Framework#121]
Going on a nature program thing. Will be back around November 17.

**Comment by GCat** [comment]
have fun! thanks for the last updates

**Comment by taotao111** [comment]
I use unit 5.3.5 open this ,but all the scene gameobjet missing the componts, 
i create a new project use unity 5.3.5 then i drag the folder to the assets and open the exampleScene,but the component scripts is missing.is step i import wrong? Thank you!

**Comment by zs3718** [comment]
class FixedMath
`public static bool MoreThanEpsilon(this long f1)
        {
            return f1 > Epsilon || f1 < Epsilon;
        }`
f1 < Epsilon or f1 < -Epsilon?
