### ISSUE TITLE
Agents from the back can't push other agents to get in attack range

### ISSUE THREAD

**Issue by GCat** [SnpM/Lockstep-Framework#123]
![123](https://cloud.githubusercontent.com/assets/9512635/21469823/e9c85f9c-ca71-11e6-9e45-71be428b9cca.png)

as in the picture, the problem gets worse as more agents are being added
they become dead weight from the back while only the front attack

**Comment by nibsbin** [comment]
In the Scan ability, uncheck ChangePriority.

**Comment by GCat** [comment]
alright thanks
