### ISSUE TITLE
Using just the physics engine?

### ISSUE THREAD

**Issue by MattFoley** [SnpM/Lockstep-Framework#134]
Hi,

Is it possible to use this framework just for the deterministic physics engine? Does that require a server? 

I have a networking solution to send data between players, player to player, but I don't have a physics engine that can recreate the physics identically on both platforms. I'd like to be able to make sure the physics play back identically on both devices (being simulated on both devices, and just passing the action data between two players in a turn based manner).

Thanks!

**Comment by nibsbin** [comment]
It is. You will still need to use agents and LockstepManager for frames but
there's no need for LS's networking features.

You can even run physics standalone with LSBody and PhysicsManager but I
haven't tried this so I don't know if it will work seamlessly.
