### ISSUE TITLE
can not run this framework on unity5.6.3

### ISSUE THREAD

**Issue by Sv7en** [SnpM/Lockstep-Framework#136]
follow the readme 
 1. Import the framework into a Unity project and open Lockstep-Framework/Example/ExampleScene
 2.  Set up the database and settings by navigating to the Lockstep/Database window or pressing Control - Shift - L.
at this step i got follow error  ,and can't load  Example_Database.asset
NullReferenceException: Object reference not set to an instance of an object
Lockstep.Data.EditorLSDatabaseWindow.OnEnable () (at Assets/Database/Editor/EditorLSDatabaseWindow.cs:41)
UnityEditor.EditorWindow:GetWindow()
Lockstep.Data.EditorLSDatabaseWindow:Menu() (at Assets/Database/Editor/EditorLSDatabaseWindow.cs:33)

**Comment by nibsbin** [comment]
Thanks for the heads up. I made some changes to the database system that should prevent a null Window.
