### ISSUE TITLE
Tutorial / Documentation

### ISSUE THREAD

**Issue by thetemplar** [SnpM/Lockstep-Framework#139]
Hey,
is it possible to get a simple Youtube-tutorial or a better documentation of the LS-Framework?
I am a bit overwhelmed by the project size and missing some information about it.

I know it is on the agenda to do, but maybe a simple youtube video is more efficient in explaining it than a longer wiki. :)

**Comment by nibsbin** [comment]
Thanks for the suggestion. I experimented with a video tutorial a while ago [on how to create/design a new agent from scratch](https://www.youtube.com/watch?v=EYqFp7dz50g).

I know the audio is spaghetti (recorded on my laptop) but besides that, do you think there are things I can significantly improve on? Re-watching the tutorial showed me a lot of things I could do better. In future tutorial videos, I'm going to draft a script and maybe have a lesson plan/series (i.e. creating basic Starcraft-eque RTS).

**Comment by thetemplar** [comment]
A very basic RTS tutorial with the LSF would be super cool and helpful.
Like with just one type of unit and building etc., just to understand the basics of how to implement the framework.

**Comment by nibsbin** [comment]
I got off my butt and started the Desert RTS tutorial series to show how to create a basic RTS and extend from there. Here's the link: https://youtu.be/5EbJa_NjdLM

Sorry for the um's and uh's. I think that'll get better with practice.

**Comment by thetemplar** [comment]
Wow nice! 
Have you a patreon or smth so I can buy you a beer? :D
And yay, my name in someones youtube vid ;-)

**Comment by nibsbin** [comment]
Thanks for the support! A patreon for the project is an awesome idea but I'm going to make useful documentation and tutorials first.

**Comment by SnpM** [comment]
Oh I thought
