### ISSUE TITLE
How can i test this framework by open two client?

### ISSUE THREAD

**Issue by cdm456852** [SnpM/Lockstep-Framework#145]
Hi! thank you so much for open source this lockstep framework, I want to know how can I play this by open two client and test the lockstep framework.

**Comment by nibsbin** [comment]
On Windows you can first build the game. Then run the .exe file 2 times.

**Comment by cdm456852** [comment]
Do not need a stand alone server?

**Comment by cdm456852** [comment]
I just tested ,the two clients don't have any connection. if there is has any ip config that I can do?

**Comment by nibsbin** [comment]
I will make a Desert RTS tutorial for setting up multiplauer this weekend.
At the moment there may be a section for setting up multiplayer in the wiki.

**Comment by cdm456852** [comment]
Thank you so much for make a multiplayer tutorial.
