### ISSUE TITLE
Is this physics engine worked on X-Y plane?

### ISSUE THREAD

**Issue by cdm456852** [SnpM/Lockstep-Framework#146]
Is this physics engine worked on X-Y plane?

**Comment by nibsbin** [comment]
Yup!

**Comment by cdm456852** [comment]
I want to know what kind of protocol this framework use, TCP UDP R-UDP KCP?

**Comment by nibsbin** [comment]
Lockstep Framework doesn't handle connections. LockstepNetworkManager.cs is
virtualized and assumes that bytes come and go correctly. You can use
Photon, Darkrift, Force, and other networking solutions for transport of
those bytes.

**Comment by cdm456852** [comment]
Thank you so much.

**Comment by cdm456852** [comment]
Thank you so much.
