### ISSUE TITLE
Open Lockstep Data window NullReferenceException

### ISSUE THREAD

**Issue by WarrenMondeville** [SnpM/Lockstep-Framework#147]
ctrl+shift+L
NullReferenceException: Object reference not set to an instance of an object
TypeReferences.ClassTypeReference.op_Implicit (TypeReferences.ClassTypeReference typeReference) (at Assets/LockstepFramework/Integration/Rotorz/ClassTypeReference/ClassTypeReference/ClassTypeReference.cs:94)
Lockstep.Data.EditorLSDatabaseWindow.get_DatabaseType () (at Assets/LockstepFramework/Database/Editor/EditorLSDatabaseWindow.cs:13)
Lockstep.Data.EditorLSDatabaseWindow.LoadDatabase (Lockstep.Data.LSDatabase database) (at Assets/LockstepFramework/Database/Editor/EditorLSDatabaseWindow.cs:170)
Lockstep.Data.EditorLSDatabaseWindow.LoadInit () (at Assets/LockstepFramework/Database/Editor/EditorLSDatabaseWindow.cs:44)
Lockstep.Data.EditorLSDatabaseWindow.OnGUI () (at Assets/LockstepFramework/Database/Editor/EditorLSDatabaseWindow.cs:63)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:272)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:265)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:232)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by proepkes** [comment]
In the Resources-Folder, check that the Database is set to Example_Database. Also it helped for me to keep the Lockstep Database-Window open all the time.

**Comment by nibsbin** [comment]
Thanks for the quick fix. I'm tracking this bug and will fix it when I get
back.

**Comment by nibsbin** [comment]
Consolidating editor-related bugs here: https://github.com/SnpM/LockstepFramework/issues/170
