### ISSUE TITLE
Desert RTS

### ISSUE THREAD

**Issue by nibsbin** [SnpM/Lockstep-Framework#149]
Hey developers! If you haven't seen it yet, I'm making a tutorial series/project for Lockstep Framework called [Desert RTS](https://github.com/SnpM/LockstepFramework/wiki/Tutorial-Series).

Unfortunately, it's my first tutorial series and I'm scrambling around a bit to tackle new topics. Are there any big rocks you want me to hit or ideas/feedback to improve the tutorial series?

**Comment by cdm456852** [comment]
What about the deterministic fog of war?

**Comment by thetemplar** [comment]
Hi!
First, thank you for the tutorial!
Regarding the content: How about some basics like 'gather ressource' or 'create building' (which creates units for those ressources maybe)?
I am still not sure how to do that with your LSF properly.

**Comment by nibsbin** [comment]
@cdm456852 Those are both huge, awesome projects. Fog of war has been on the roadmap for a while but I ran into a lot of bugs and irl stuff while working on it. Making an efficient fog of war system for the number of units LSF is designed for wasn't easy.

Thanks for letting me know about the demand for this feature. It gets into math/grid stuff so I probably won't make tutorials for the development (but definitely for implementing/configuring). Now that I have more time, I will do my best to get this feature into the game.

@thetemplar Resource gathering/management and building creation sound like awesome features to dive into! Both seem a bit more involved so I'll start a sub-series like "Desert RTS #7.1 - Resource Gathering Part 1".

**Comment by cdm456852** [comment]
@SnpM Thank you so much for your brilliant work!!

**Comment by thetemplar** [comment]
Yes, thanks you for your work!

**Comment by thetemplar** [comment]
Thanks for the new tutorials by the way.
Because you asked for more ideas: How about opening LSF in MonoDev and briefly explain the files and the concept behind the important classes (the ones users do come in contact with for example)? Its not as annoying as real documentation, but gives a good idea about the LSF :)

**Comment by nibsbin** [comment]
Oh great idea! I just made Ghost bodies so I can run through that new
feature and go through the physics system. FoW can include an explanation
for thr grid system. Hierarchical pathfinding or other optimizations would
lay out the pathfinding system.

**Comment by thetemplar** [comment]
How are things going?
Any chance to make some new, great tutorials?
Like resource gathering or the explain-every-file/class-briefly-video?

Cheers!

**Comment by nibsbin** [comment]
@thetemplar Hey man, sorry I've been dealing with some stuff. I will prioritize this project and do my best to deliver.

**Comment by thetemplar** [comment]
Hey
No worries! But happy to hear new videos will come soon.

**Comment by thetemplar** [comment]
So...? Is this still a thing? :)

**Comment by itaifish** [comment]
^ Would love to see this continued

**Comment by proepkes** [comment]
https://github.com/proepkes/UnityLockstep the modern way of deterministic multiplayer with clientside prediction/rollback
The todo's currently stack up, looking for contribution since the networking part is getting stable
Two players stay in sync even with high ping/high packet drop

**Comment by nibsbin** [comment]
I don't have plans to continue Desert RTS at the moment :(
