### ISSUE TITLE
DynamicBlocker

### ISSUE THREAD

**Issue by cdm456852** [SnpM/Lockstep-Framework#150]
when you call DynamicBlocker.OnDeactivate(),the pathfinding System still believe this block is unpassable.  
  I resolve it by setting GridNode._clearanceDegree=1
 when (unwalkable==false&&_clearanceDegree==0) in the function GridNode.UpdateClearance()

**Comment by nibsbin** [comment]
Spotted some bugs in clearance degree calculations. Also capped clearance degree to 8 for dynamic grid update performance.
