### ISSUE TITLE
Bug about circle collider

### ISSUE THREAD

**Issue by DogsLike** [SnpM/Lockstep-Framework#151]
Bug happens when I add a new blocker at ExampleScene. The blocker object is just a wall copy with Unity LS Body Shape circle.  It seems circle collider doesnt work correct. Unity 2018.1.3.

**Comment by thetemplar** [comment]
Did you "Scan and Save" in the Manager-Object/Enviroment Helper?

**Comment by DogsLike** [comment]
Yes i did. here is error log.
![222](https://user-images.githubusercontent.com/5936439/41460875-9b5829c2-70c0-11e8-8718-c89765325bba.png)
![11111](https://user-images.githubusercontent.com/5936439/41460883-9f43e670-70c0-11e8-85cf-8bdf03a269bd.png)

**Comment by DogsLike** [comment]
It seems agent cant spawn correctly.
![333](https://user-images.githubusercontent.com/5936439/41460943-d20bde82-70c0-11e8-8bc1-122a580a4a5b.png)

**Comment by DogsLike** [comment]
Fixd by keep Database Window open.
