### ISSUE TITLE
How can I add ability to agent during runing time ?

### ISSUE THREAD

**Issue by DogsLike** [SnpM/Lockstep-Framework#153]
if my agent get a medkit. I want my agent get heal ability. How can I do it?

**Comment by nibsbin** [comment]
Hey DogsLike. Modify the Health ability by calling:

LSAgent agent:
agent.GetAbility<Health>().TakeDamage(-HealAmount)

I'll make a function that's more intuitive but taking negative damage is
the equivalent of healing at the moment.
