### ISSUE TITLE
ExampleScene broken?

### ISSUE THREAD

**Issue by zzuumm** [SnpM/Lockstep-Framework#154]
Hey, I just found the framework and I'm excited to see what I can do with it. I'm only wondering if the ExampleScene scene is broken some way. When the game is started the units are scattered in the map in a long line formation (some are outside and complaining "No node at position") and there doesn't seem to be any sort of movement or selection interaction with the units. Also, Manager object prefab connection is missing and it's showing in red in the hierarchy view. I'm using Unity 2017.3.1f1

**Comment by nibsbin** [comment]
Hi zzuumm. There were some bugs with the GhostLSBody system that affected the example scene. I reverted those commits so the latest version of Master should be good to go.
