### ISSUE TITLE
Room for Simulate() Optimizations?

### ISSUE THREAD

**Issue by zzuumm** [SnpM/Lockstep-Framework#156]
I notice that when there is a considerable number of agents in the scene (talking about >400 in my case) I start to get lag, and my machine is rather powerful compared to low-end or mobile devices. I'm wondering if this could be improved by not calling Simulate() on every FixedUpdate() but instead keep a "dirty" list of those who need to? This especially considers LSAgent instances and maybe even more specifically their abilitymanager simulation round.

Oh, how I tested this was just the ExampleScene (it's working now, thank you) and spawning default TestAgents as in tutorial part 2.

**Comment by nibsbin** [comment]
The main issue is collision detection scaling quadratically. Partitioning
and culling significantly reduce unnecessary collision checks but there's
still a lot of iterating and collection accessing.

Fortunately, many of those calls can be optimized by the compiler. Try
building the project and running it as a standalone. On my laptoaster, I
can comfortably hit >1k objects with environment colliders while recording
but definitely not 400 in the editor.
