### ISSUE TITLE
Problem of NullReferenceException

### ISSUE THREAD

**Issue by JourneyHans** [SnpM/Lockstep-Framework#165]
I use Unity 2018.2.8f1 and I get an NullReferenceException at ReorderableListControl.cs, line 568:

`_visibleRect = GUIHelper.VisibleRect()`

I find solution of this bug, it seems like Unity 2018 changed visibleRect's access. At GUIHelper.cs, change

`var piVisibleRect = tyGUIClip.GetProperty("visibleRect", BindingFlags.Static | BindingFlags.Public);`

to

`var piVisibleRect = tyGUIClip.GetProperty("visibleRect", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic); `

will solve that.

**Comment by JourneyHans** [comment]
Oh, sorry, there are still one more place should be changed. Still at GUIHelper.cs, change

`VisibleRect = (Func<Rect>)Delegate.CreateDelegate(typeof(Func<Rect>), piVisibleRect.GetGetMethod());`

to 

`var getMethod = piVisibleRect.GetGetMethod(true) ?? piVisibleRect.GetGetMethod(false);`
`VisibleRect = (Func<Rect>)Delegate.CreateDelegate(typeof(Func<Rect>), getMethod);`

**Comment by JourneyHans** [comment]
I found solution at here: https://github.com/pbhogan/InControl/pull/217/commits/2198c7de893370d903b16196ffb1261fafe1bf6f

**Comment by nibsbin** [comment]
Consolidating editor-related bugs here: https://github.com/SnpM/LockstepFramework/issues/170
