### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by slimshader** [SnpM/Lockstep-Framework#169]
Hey, this project looks really good but there are issues with Unity >= 2018, is it still maintained?

**Comment by sili3011** [comment]
To use it with Unity >= 2018, have a look here: https://bitbucket.org/rotorz/reorderable-list-editor-field-for-unity/commits/6b1c21e6a60a
Adjust your GUIHelper and that should do the trick!

**Comment by nibsbin** [comment]
Hey @slimshader , thanks for checking out the project. I had big plans for LockstepFramework.NET but got bombarded by life. This month, I'm going to make sure all the current features are stable then cut future development plans. Working on LS has been an awesome pleasure.

**Comment by nibsbin** [comment]
Consolidating editor-related bugs here: https://github.com/SnpM/LockstepFramework/issues/170
