### ISSUE TITLE
Plan for Lockstep Framework

### ISSUE THREAD

**Issue by nibsbin** [SnpM/Lockstep-Framework#171]
I'm officially taking steps to stop developing Lockstep Framework. Working on Lockstep Framework has been my amazing opportunity, pleasure, and learning experience. Unfortunately, life and laziness get in the way of investing as much time as I did in the past working on the project. College, career, and cybersecurity are my priorities now.

This month will be dedicated to refining the project and its current features by documenting, bug-fixing, and maintaining with the latest Unity versions. All large new features are cut (e.g. fog of war, vector-field pathfinding). After this month, the project will always be open source but I'm going to let go of the reins.

-- John

**Comment by nibsbin** [comment]
Continuing the Desert RTS series in place of documentation.
https://www.youtube.com/watch?v=Fsz5SqQ6QSk&feature=youtu.be

**Comment by DogsLike** [comment]
I'm sad to know this. Lockstep Framework is really valuable, and I'm Building my own game with it. 
But best wishes.

**Comment by mrdav30** [comment]
John, I really appreciate your hard work and am dedicated to finishing this project.  If you or anyone in the future wishes to help with this endeavor, check out my repo LockstepRTSEngine

[](https://github.com/mrdav30/LockstepRTSEngine)
