### ISSUE TITLE
can not run this framewodk on unity2018.3

### ISSUE THREAD

**Issue by Ecstasyzzz** [SnpM/Lockstep-Framework#172]
The first time import the framework into a Unity project and open Lockstep-Framework/Example/ExampleScene, the console give me that : 
Failed to load 'D:/Unity2018.3Project/copyAnimator/Assets/LockstepFramework-Master/Example/Terrain/TestTerrain.asset' because it was serialized with a newer version of Unity. (Has a higher SerializedFile version)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Can you tell me what the version is? Thanks!

**Comment by nibsbin** [comment]
The latest commit targets Unity 2019.1f1.

2018.3 may work by recreating the terrain file and gameobject in the
ExampleScene (but I haven't tested this Unity version).

**Comment by Ecstasyzzz** [comment]
thank you for let me know
