### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by NVentimiglia** [SnpM/Lockstep-Framework#27]
After a little trial I was able to get the project built and running without errors. That said, nothing is happening. I know you had mentioned that better examples are coming, but, I don't see any activity in the included example scene. Can you comment on this ?

**Comment by nibsbin** [comment]
Looking into it. I might've changed the example scene after being lazy and using it for testing. Cloning a fresh copy and trying it out...

**Comment by nibsbin** [comment]
There were 2 main bugs. The first was from inputs recently being changed to be dynamically registered in the database. The other was from LSBody now not automatically setting the PositionalTransform and RotationalTransform at runtime. TestAgent was never updated for this change, so it didn't have transforms to update with its position and rotation. As of the last commit, ExampleScene should work.
