### ISSUE TITLE
Is there any special reason that fixed point number is implemented as static helper?

### ISSUE THREAD

**Issue by wuyuntao** [SnpM/Lockstep-Framework#30]
In DPhysics, fixed point number is implemented as a struct which I suppose is easy to use and understand. But in LFS, fixed point number should be declared as long and used via a static helper.

Is there any special reason to implement it in this way?

**Comment by nibsbin** [comment]
Primitives like 'long' are much faster than structs and less of a pain to serialize. 

According to a test without release optimizations, long is more than twice as fast as FInt for operators which means that the struct accrues some considerable overhead for operator overloading and accessing the stored long. I haven't tested passing them through parameters but structs are apparently copied around and not inlined.

**Comment by wuyuntao** [comment]
Thank you for explanation :-)
