### ISSUE TITLE
replay in GUI doesn't replay deterministically

### ISSUE THREAD

**Issue by GCat** [SnpM/Lockstep-Framework#64]
In the example scene, try and move around the objects, collide with each other
then press replay, the result will be 90% the same but not 100%
the longer it will play the more you will notice the desync

**Comment by GCat** [comment]
Never mind I've noticed environment helper is needed at the beginning to initialize the first pos
seems like a false bug :+1:

**Comment by nibsbin** [comment]
I added something to test determinism... a BehaviourHelper called
DeterminismTester. That might help you determine when and how a desync
occurs.

**Comment by nibsbin** [comment]
Ah, nevermind. But keep DeterminismTester in mind!
