### ISSUE TITLE
grouping units near a polygon LSBody

### ISSUE THREAD

**Issue by GCat** [SnpM/Lockstep-Framework#67]
While grouping units near a polygon LSBody like in the picture
the units push each other into a LSBody polygon object

this bug won't occur if the LSBody is a Circle / AA Box, only in a Polygon

![screenshot 2016-03-22 20 46 35](https://cloud.githubusercontent.com/assets/9512635/13964248/7b6cdeb8-f071-11e5-8ca3-1df1512b62af.png)

it will also cause an error
`OverflowException: Number overflow.
Lockstep.Array2D 1[Lockstep.PartitionNode].Resize (Int32 newWidth, Int32 newHeight) (at Assets/LockstepFramework-Develop/Core/Utility/Array2D.cs:113)`

**Comment by nibsbin** [comment]
This seems like a partitioning issue. I'll look into it. Is there any difference with the most recent merge?

**Comment by GCat** [comment]
even in the most recent merge, same bug.

**Comment by nibsbin** [comment]
I'm having trouble reproducing the bug. What's the behaviour with just 1 agent? Also, what's the position of the polygon?

**Comment by GCat** [comment]
As Is, in the ExampleScene
just spawn 60 agents and let them idle near the polygon
no need to change/add anything

**Comment by nibsbin** [comment]
Ah, thanks for the info. Reproduced it successfully.

**Comment by nibsbin** [comment]
I spotted some collision detection bugs that might've shot units to a buggy place. I can't get the bug again, so I'm going to close the issue. If you happen to get the bug again, open it back up or make new issue and I'll explore more deeply.

**Comment by GCat** [comment]
You fixed it.  great work :clap:

**Comment by t4world** [comment]
Assets/Core/Simulation/Physics/Raycast/Raycaster.cs(4,7): error CS0246: The type or namespace name `PanLineAlgorithm' could not be found. Are you missing a using directive or an assembly reference?

**Comment by nibsbin** [comment]
Make sure you pull the submodules.
