### ISSUE TITLE
If agents dies they won't collide with each other after they respawn

### ISSUE THREAD

**Issue by GCat** [SnpM/Lockstep-Framework#73]
When multiple agents spawn on the same position they collide fine,

but after they all die(), if you re-spawn them all in one position, they wont collide with one another

**Comment by nibsbin** [comment]
Are they colliding when not spawned on the same position?

**Comment by GCat** [comment]
Yep

**Comment by nibsbin** [comment]
Thanks for letting me know. Going to look into it.

**Comment by nibsbin** [comment]
Solved
