### ISSUE TITLE
Why was GetStateHash used as a name over GetHashCode?

### ISSUE THREAD

**Issue by erebuswolf** [SnpM/Lockstep-Framework#76]
I am going through the code and cleaning up as many warnings and issues as I can to tidy it up before diving into the project I want to make with it. What was the motivation to use GetStateHash as the name for the hash code method for all objects over the default GetHashCode that should be overriden in all of these objects with the logic implemented in GetStateHash. Is there something special about the StateHash that means it shouldn't be used in all GetHashCode calls? If not I'll make a pull request renaming all instances of GetStateHash to GetHashCode, or if people prefer keep GetStateHash and add a GetHashCode that simply calls GetStateHash.

**Comment by nibsbin** [comment]
On AgentController, GetStateHash is static. It returns a hash of all AC
instances for validation. I'm not sure why Vector2d doesn't use GetHashCode
though. A pull renaming the GetStateHash to GetHashCode would be great.
