### ISSUE TITLE
Avoidance Priority

### ISSUE THREAD

**Issue by sooonism** [SnpM/Lockstep-Framework#84]
Is there a way to set an avoidance priority? 
Just like how it works in Unity3d Navmesh Agent. The high priority agent in away can push low priority agent. And the low priority agent will have to find other path if high priority agent is in a way.

**Comment by nibsbin** [comment]
Yeah, LSBody.Priority

**Comment by sooonism** [comment]
There are no Priority in Inspector. Do you mean base priority? I tried to change it but it seems like nothing happen.

**Comment by sooonism** [comment]
OK, I found it. Strange that it did not show up in Inspector even it is public.

**Comment by sooonism** [comment]
OK, I found it. Strange that it did not show up in Inspector even it is public.
