### ISSUE TITLE
How can I set the move speed with script?

### ISSUE THREAD

**Issue by sooonism** [SnpM/Lockstep-Framework#85]
I need to set the speed in <Move>() with code. So I tweak the code a bit:

`public virtual long Speed
        {
            get { return _speed ; }
            set
            { _speed = value;}
        }`

However, whatever number I send in, it will give me some funny floating number:

`instance.GetComponent<Move>().Speed = 6; //I will get  9.1552734375e-05, I don't know why`

This is the first time I am using long number and based on my research it should only give me back 6. 

What seems to be the problem here? 

Or is there a better way for me to set the `Speed` ?

**Comment by nibsbin** [comment]
Make sure to use the FixedMath library.

Agent.GetAbility<Move>().Speed = FixedMath.Create (6);

or

Agent.GetAbility<Move>().Speed = FixedMath.One \* 6;
