### ISSUE TITLE
Desync in playback

### ISSUE THREAD

**Issue by korbul** [SnpM/Lockstep-Framework#88]
I'm using Unity 5.4.0f3.

Massive desync in playback. I play the example scene and then press save. It tries to playback what happens the first time yet the simulation desyncs from the first frame. The desync can be visually observed but I also used the DeterminismTester.

Also an argument null exception is thrown when I press the rewind button.

here is gif illustrating the issue
http://i.imgur.com/z6XcHNi.gif

**Comment by nibsbin** [comment]
Thanks for catching this bug and providing that info. Just got it fixed.

The bug had to do with replay deserialization. Frames were skewed so all commands in the replay were executed 2 frames earlier. Also, AutoSpawn created a command when the game started that was also serialized in the replay. I added a guard to prevent non-replay commands from being registered while a replay is active.
