### ISSUE TITLE
ScanNode.BucketsWithAllegiance() causes a dramatically gc?

### ISSUE THREAD

**Issue by maxin0628** [SnpM/Lockstep-Framework#99]
Hello John,

I uses this framework in mobile game, as issue title describe, when I checked performance via profiler, I found this function had been called in a huge number and making a gc allocate frequently. 

This may be not an "issue" for desktop, but this count of gc impacts frame rate dramatically on mobile devices, I've researched it for a while, but can't find a solution, could you please take a look at this function, and give some advice?

thanks
Johnson

**Comment by nibsbin** [comment]
Ah, thanks for notifying me. Going to fix this soon.

**Comment by maxin0628** [comment]
Big thanks!!! Silky smooth on mobile phone now!
